export const TOGGLE_AUTH_STATE = "TOGGLE_AUTH_STATE";
export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const TOGGLE_NEWS_FETCHING_STATE = "TOGGLE_NEWS_FETCHING_STATE";
export const GET_NEWS = "GET_NEWS";
